layout/_partial/after-footer.ejs
不知道为什么您需要这样判断，但是在我的博客中会出问题，评论全部消失了，改为标准的 disqus embed 模式就好了
=> fix disqus comment disappear

languages/id.yml
Hi, thanks for the beautiful theme :smiley: 
id.yml demo here: http://ekajogja.github.io
=> Created id.yml

_config.yml.example, layout/_partial/article.ejs, layout/_partial/head.ejs, layout/_partial/post/banner.ejs, layout/_partial/post/thumbnail.ejs, layout/_widget/links.ejs, source/css/_partial/article.styl, source/css/_partial/highlight.styl
Hi! Thanks for this great template, I just discovered Hexo and  adopted with your theme!
I have added the possibility to put a banner on top of the post `post.banner` and a thumbnail image for the sidebar `post.thumbnail`. Sidebar select in this order, post thumbnail, post banner or post image.
I have added an option for custom stylesheet. Stylesheet can be added to `sources/css`. Its for site who needs some adjustments and custom configuration.
And I tried to correct Gist integration, but still persist line numbers height not the same of line height.
=> Some additionals options

_config.yml.example
sove the problem 'Cannot GET /archives' 'Cannot GET /tags' etc..
just go theme/_config.yml   menu   delete  "/"
=> delete  " / "

layout/_partial/post/thumbnail.ejs
Signed-off-by: Xiaofeng QU <xiaofeng.qu.hk@ieee.org>
=> Choose a thumbnail from the photos of the post without a thumbnail nor a banner

languages/en.yml, languages/zh-CN.yml, layout/_partial/article.ejs, source/css/_partial/article.styl
[Article catalogue demo](http://zhengxiaopeng.com/2015/05/05/%E3%80%90%E8%AF%91%E3%80%91NotRxJava%E6%87%92%E4%BA%BA%E4%B8%93%E7%94%A8%E6%8C%87%E5%8D%97/)
Fix I18N ; )
=> Support article catalogue

languages/ja.yml
Thanks for the really nice theme!
Here is the language file for Japanese :smile:
=> Created a language file for Japanese

_config.yml.example, languages/es.yml, layout/_partial/after-footer.ejs, layout/_partial/cdn_after_footer.ejs, layout/_partial/cdn_head.ejs, layout/_partial/google_site_verification.ejs, layout/_partial/head.ejs
Hi!
(sorry for my bad english)
- Added Spanish
- Added Google Websmater tools support
- More speed in loading page for America and Europe
- I changed all scripts and fonts from "useso.com" for the google host, See the diference in the page loading time:
(Useso is good for china but outside it is very slow)
=> Spanish + Google Websmaster tools + More speed in loading page for America and Europe

languages/zh-TW.yml
To support the language `zh-TW`
=> Added language 'zh-TW'

languages/ru.yml
Hello!
You forgot to add one important line in the translation file.
=> Add "Read More" for Russian translation

languages/ko.yml
Thank you for awesome theme.
I would be happy for that you add my Korean language file.
=> Add Korean version language file

layout/common/head.ejs
Add lang attribute for web accessibility.
=> Add lang attribute to html tag

layout/common/profile.ejs
We don't need to count unpublished tags.
=> Fix tag count correctly.

layout/common/profile.ejs
RT, we should set gravatar size parameter.
=> set gravatar size parameter

layout/common/sidebar.ejs, source/css/_partial/sidebar.styl, source/js/main.js
=> redesign button toTop, show or hide button improved

languages/zh-TW.yml
To Add 'Read more' translation
=> translation: add missing part of zh_TW

_config.yml.example, layout/comment/gitment.ejs, layout/comment/index.ejs, layout/comment/scripts.ejs
- Add a new comment module for Github users.
=> Add gitment module.

_config.yml.example, layout/comment/counter.ejs, layout/comment/index.ejs, layout/comment/livere.ejs, layout/comment/scripts.ejs
sample see http://www.hidennis.tech/2017/08/12/icarus-support-livere/
=> add livere comment plugin support

_config.yml.example, layout/comment/index.ejs, layout/comment/scripts.ejs, layout/comment/valine.ejs
add [Valine comment system](https://github.com/xCss/Valine) support
=> Add: add Valine comment system support

includes/specs/plugins.spec.js, layout/common/article.ejs, layout/common/footer.ejs, layout/plugin/visit.ejs
Show PV/UV of blog and PV of each article
=> Show PV/UV of blog and PV of each article

source/css/search.css
Make close button in search centered vertically (#444)
=> Make close button in search centered vertically (#444)

layout/widget/profile.ejs
Fix avatar deformation when all widgets are on the left
=> Fix avatar deformation when all widgets are on the left

README.md, includes/specs/comment.spec.js, includes/specs/donate.spec.js, includes/specs/footer.spec.js, includes/specs/navbar.spec.js, includes/specs/plugins.spec.js, includes/specs/providers.spec.js, includes/specs/search.spec.js, includes/specs/share.spec.js, includes/specs/sidebar.spec.js, includes/specs/widgets.spec.js, layout/common/footer.ejs
- Update links to HTTPS.
- Correct broken links.
=> Update links to HTTPS and fix broken links

languages/pl.yml
This is polish translations to the project. At least this way I can say thank you! :)
=> Added translation to Polish language

layout/widget/profile.ejs
=> fix avatar rounded.

layout/widget/toc.ejs
当目录为空的时候，就不要生成目录这个widget了，生成一个空的看起来也有点奇怪
=> 当目录为空的时候，就不要生成目录这个widget了，看起来有点奇怪

layout/widget/toc.ejs
=> fix(widget):build error

layout/widget/profile.ejs
click number forward Corresponding page.
=> opt(profile): add statistics data forword page

layout/widget/subscribe_email.ejs
=> opt(widget):button color

source/js/main.js
=> add someone code folded

languages/de.yml
Hello,
I added a language file for german, country code 'de'
Have a nice day 😄
=> added german language ('de')

layout/widget/subscribe_email.jsx
=> fix(widget): subscription description layout issue

layout/widget/links.jsx
Recommendation links should link to correct URL.
=> fix(widget): incorrect links href

source/css/base.styl, source/js/main.js
=> fix(base.styl):css

source/js/main.js
=> fix(layout): code block copy button layout on mobile

source/js/main.js
=> fix(main.js):catch exp

includes/helpers/site.js
问题：markdown中添加了部分html代码和plantUml代码，之后hexo g就报错，根据报错代码行修改的，修改后ok了。
=> fix bug wordcount

includes/specs/donate.spec.js
`categories/Donation` --> `categories/Plugins/Donation`
=> Fix wrong link

source/_posts/zh-CN/Getting-Started.md
Add one external link to zh-CN getting started doc.
活用 Bulma 美化 Icarus 文章
https://www.imaegoo.com/2020/icarus-with-bulma/
=> chore(doc): add external link

layout/common/article.jsx
feat(author):add author if exists
=> feat(author):add author if exists

include/style/base.styl
`include/style/base.styl`
美化了滚动条样式
个人感觉默认的滚动条不太漂亮，遂修改了滚动条样式，使其与主题风格更加统一（只是我觉得），我不是专业前端，对于样式、颜色等方面拿捏得不准，请见谅。
@ppoffice 大佬可以考虑一下，是否需要修改滚动条样式，如果不需要修改，关闭 pr 即可；如果要修改，我提交的样式是否需要继续调整一下。
=> beautify srollbar

source/_posts/en/Comment-Plugins.md, source/_posts/zh-CN/Comment-Plugins.md
Changyan removed the restrictions on ICP license.
http://changyan.kuaizhan.com/static/help/o-beian.html
=> Remove warnings about ICP license

include/style/article.styl
detailed discussion has been finished in [hexo-component-inferno#18](https://github.com/ppoffice/hexo-component-inferno/pull/18) and seemingly considered ok. this PR intends to put an end to the improvements of the component repo.
=> feat(widget): accompanying CSS-tuning of hexo-component-inferno#18

include/style/navbar.styl, layout/common/navbar.jsx
@ppoffice Feel free to merge it.
=> Fix the NavBar Overflow Issue when NavBar Items are Too Many

include/schema/common/comment.json
=> Add the missing Twikoo schema to comment.json

include/style/plugin.styl
=> Fix MathJax Overflow Issue

include/schema/common/footer.json, layout/common/footer.jsx
Reverts ppoffice/hexo-theme-icarus#1171
=> Revert "feat(footer): added copyright"

.eslintrc.json, .gitignore, include/schema/common/footer.json, layout/common/footer.jsx
=> [Done] Fix #1171

include/schema/config.json
=> Fix configuration file version issue

languages/it.yml
=> create it.yml - itlaian translation

package.json
dependencies:
- [#71](https://github.com/ppoffice/hexo-component-inferno/pull/71)
=> chore: bump hexo-component-inferno version

layout/common/article.jsx
feat(core): Add pin icon for pinned articles on homepage (issue #1337)
Previous:
Now:
=> feat(core): Add pin icon for pinned articles on homepage (issue #1337)
