- README.md
- _config.yml.example
- layout/_partial/header.ejs
Example:
if website is `xxx.github.io/blog`, the `Logo` will link to `xxx.github.io/`
Solution:
replace path `/` to `.`
***Thanks for the wonderful theme!!***
> [bug fix] if website is in subdirectory, the 'Logo' will link to wrong url

- layout/_partial/footer.ejs
The copyright could start from before. When the theme is used in a continuous blog, the posts could be written long before the current date.
To enable this function, a `since` should be set in the config file. For example, 
in `_config.yml`
```
since: 2012
```
Signed-off-by: Xiaofeng QU <xiaofeng.qu.hk@ieee.org>
> Added `since` to the copyright line

- layout/_partial/footer.ejs
Added a test of `config.since`. Just in case the `since` is the same as current year, avoiding showing `© 2015 - 2015`.
The code is not pretty. But I don't know how to set a variable in this case. Maybe someone could improve this?
Signed-off-by: Xiaofeng QU <xiaofeng.qu.hk@ieee.org>
> Add a condition for the since config

- languages/en.yml
- languages/id.yml
- languages/zh-CN.yml
- layout/_partial/post/nav.ejs
Make the “older” and “newer” links in article navigation support i18n
Indonesian translated by Google.
> Make article nav support i18n

- _source/about/index.md
This PR adds `_source/about/index.md` to match the live preview.  Without this addition, even after the user copies the themes' `_source` files, clicking on the 'About' link results in a 404.
> Add about page in theme _source

- layout/_partial/cdn_after_footer.ejs
- layout/_partial/cdn_head.ejs
As described in the article https://servers.ustclug.org/2014/06/blog-googlefonts-speedup/ , the Google libraries mirror service provided by USTC should be reasonably faster and more reliable than the one 360 offers, which even couldn't be correctly loaded over HTTPS due to certificate domain problem.
> Add USTC CDN

- LICENSE
Hello @ppoffice,
Although Tommy Chen wrote Hexo, **you** are the author of the Icarus theme, so your name should be first and foremost in the LICENSE file.  This is important because other projects porting your theme for other static site generators carries the same mistake, see how Tommy's rather than your name listed here: https://github.com/digitalcraftsman/hugo-icarus-theme/blob/master/LICENSE.md
If you feel that your theme (according to what you have committed in this repository) contains substantial code from Tommy Chen, then you may consider listing both names in the beginning like this:
Copyright (c) 2015 ZHANG Ruipeng
Copyright (c) 2013 Tommy Chen
Of course, if you prefer, you may also use "Ruipeng Zhang" instead of "ZHANG Ruipeng".  This pull request is merely a suggestion.
Note …
> Correct author information in LICENSE file

- languages/en.yml
'recents' is not a work.  This should be 'recent'.
> English spelling correction

- layout/common/thumbnail.ejs
In `hexo@3.2.0`, the implementation of `url_for` has been changed.
Please help to check out whether this commit will cause any side-effect.
Thanks.
> [bug fix] thumbnail refer to incorrect image url when site is put in a subdirectory

- _config.yml.example
- layout/common/profile.ejs
- source/css/_partial/article.styl
- source/css/_partial/profile.styl
Just two minor fix/improvements:
1) There was a small space on the right side of the share box (see the image below) on Firefox (Windows and Ubuntu) and Chrome (Ubuntu only). I've fixed it just by reducing the text box padding.
2) I've included an option to enable or disable the social link tooltips. I've kept they enabled by default, even when the option is omitted. This way no one needs to modify their current config file to re-enable the tooltips.
> Minor improvements

- layout/comment/disqus.ejs
The `universal code` for disqus is as follows. The existing script template doesn't seems to be working.
```
<div id="disqus_thread"></div>
<script>
/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
*/
/*
var disqus_config = function () {
this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};
*/
(function() {  // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = '//' + disqus_shortname + '.disqus.com/embed.js'; …
```
> Updated disqus script with configuration-variables

- source/css/_partial/article.styl
I found the blockquote obscures the toc directory.
Fix before:
Fix after:
> update blockquote position in article.styl

- source/js/main.js
We can easily add lazy loading to the theme thanks to the builtin functionalities of lightGallery. Please see my post [here](https://alendev.hopto.org/myblog/Hexo/Icarus-Theme/lazyimages/2017/07/17/) to understand how you can optionally modify your markup to access this additional and optional functionality
> Added support for lazyloading of images

- _config.yml.example
- layout/common/profile.ejs
- source/css/_partial/profile.styl
- source/js/main.js
效果如下：
配置文件添加：
`customize.profile.fixed` （可以打开关闭该特性）
并且顺便改了下 `toTop` `$(document).on('scroll', function () {}`  当页面滚动时，不会因反复执行DOM操作而导致页面不太流畅
`#profile` 的 FadeIn 效果使用 CSS 的 animation 也许更流畅。建议 `#toTop` 也用 CSS 来 FadeIn
> 添加支持固定 #profile，优化 #toTop

- source/js/main.js
配置文件设置为两栏布局 `widgets: /` 然后固定 #profile `customize.profile.fixed: true` 无效
两栏布局时 `$('#sidebar').length` 返回 false，`固定 #profile 功能`会和 `#toTop` 同时禁用
将 `if ($('#sidebar').length) { }` 中的 checkFixedProfile(); 移出来
> 修复两栏布局不能固定 #profile 的问题

- layout/comment/gittalk.ejs
Add gittalk comment plugin support.
In `_config.yml`:
```yaml
comment:
type: gittalk
owner: xxxxxxxx         # (required) GitHub user name
admin: xxxxxxxx         # (required) GitHub user name
repo: xxxxxxxx          # (required) GitHub repository name
client_id:  xxxxxxxx     # (required) OAuth application client id
client_secret: xxxxxxxx # (required) OAuth application client secret
```
> Add Gittalk comment

- layout/widget/profile.ejs
I believe it's more user-friendly to open the follow link in a new tab, as viewers may want to view other contents of the website.
> Make follow link in profile widget be opened in new tab

- layout/common/head.ejs
Really simple canonical link when `canonical_url` provided in front matter
At least a start of #435.
> Simple canonical link provided via `canonical_url` within front matter

- layout/share/addtoany.ejs
Google Plus is no more. Makes no sense in displaying it by default.
> Update AddtoAny Widget

- languages/en.yml
- languages/zh-TW.yml
- layout/widget/subscribe_email.ejs
- layout/widget/subscribe_email.locals.js
Add a subscribe email widget currently only support [feedburner](https://feedburner.google.com)
Live Demo: https://blog.liyang.info
config example
```yml
widgets:
-
type: subscribe_email
feedburner_id: LiyangsBlog
description: 現在就訂閱，新知不漏接
position: right
```
> Add subscribe email widget

- languages/ko.yml
Maybe previous translator misunderstood `about` words.
In this context, that translation means 'about me' not 'about XX words'.
> chore(*): fix mistranslated word

- includes/specs/meta.spec.js
Already added `canonical_url` config by #436.
But because config spec is missing, auto-generated config dosen't generate `canonical_url`.
Added `canonical_url` to config spec.
> feat(spec): add canonical_url spec

- layout/comment/valine.ejs
Valine default CDN is really slow and unstable. Js file load failure causes blocked page rendering. 
I've been meet it many times in a few days. So it‘s a very bad experience for site user.
Screenshot as follows:
Use theme default cdn `jsdelivr`. The test result is satisfactory, at least without failure.
Screenshot as follows:
> fix(cdn): default valine cdn response is slow and unstable

- layout/common/article.jsx
In article list page, visitor counts for articles is incorrect, the first article shows a large count of visitors, and others shows a count of 0.
Such as:
Article 1 ... 👀1234
Article 2 ... 👀0
Article 3 ... 👀0
......
We can only see the correct visitors count after click into the article.
We may remove visitor counter from article list, should we? @ppoffice
> fix(plugin): remove visitor counter from article list

- includes/specs/comment.spec.js
- layout/comment/utterances.ejs
- layout/comment/utterances.locals.js
A lightweight comments widget built on GitHub issues. Use GitHub issues for blog comments, wiki pages and more!
- [Open source](https://github.com/utterance). 🙌
- No tracking, no ads, always free. 📡🚫
- No lock-in. All data stored in GitHub issues. 🔓
- Styled with [Primer](http://primer.style/), the css toolkit that powers GitHub. 💅
- Dark theme. 🌘
- Lightweight. Vanilla TypeScript. No font downloads, JavaScript frameworks or polyfills for evergreen browsers. 🐦🌲
**Please refer to the [official website](https://utteranc.es/) for usage and demonstration effect**
Example for`_config.yml`
```yaml
comment:
type: utterances
repo: <username/repo>
issue-term: pathname
label: comment
theme: github-light
```
> Add Utterances comment system

- include/style/article.styl
Long content in `<code>`  will overflow and cause horizontal scrollbar on mobile phones
> fix: code tag text overflow-wrap

- include/style/plugin.styl
做了以下四点改进：
首先，由于数学公式(MathJax & KaTeX)在移动端容易出现水平方向超长的状况，该改进自动加入水平滚动条；
其次，数学公式(KaTeX)在某些移动端会出现顶部显示不全的状况，该改进通过增加上方内边距(padding-top)，减少上方外边距(margin-top)来解决该问题，由于增加和减少的边距相同，该变动不会造成其它的排版上的影响；
再来，内联的数学公式(KaTeX)可能在公式中的任意位置换行，这是我们不想看到的，所以该改进禁止其换行(whitespace: nowrap;)
最后，如果在数学公式(KaTeX)中使用 `\tag{...}` 给公式编号，最后生成的公式中会对应地产生一个 class 为 `.tag` 的 HTML 标签。不巧的是 bulma 框架中规定了 `.tag` 的样式，这会使公式的标签看上去很奇怪，所以该改进将本不该有的对于 `.tag` 的样式设定为了 unset 来解决该问题。
> fix(style): improve MathJax and KaTeX

- include/style/search.styl
#719
Tested with
1. Windows + Chrome 71
2. Windows + Chrome 81
3. Windows + Firefox 76
4. Android + Chrome 71
5. Android + Wechat browser
6. iPad OS + Safari
> fix(css): search box height issue on chrome 71

- include/style/article.styl
fix(style): fix style of post navigation
Fix style of post navigation for long title.  In released version, navigation will overflow the screen with a long title.
修复因标题过长而导致的文章导航样式问题。现时版本於手机等移动设备浏览时，若标题过长，导航提示可能会溢出屏幕。
Here are some pages for demo.
此处提供两个页面以供参考。
[Kitcham's Blog - 为 ICARUS 而生的友情链接页面](https://blog.uiharu.top/archives/feat-icarus-links-page.html)
[Kitcham's Blog - 计算神经科学（一） —— 我们搞清楚自己的脑子了吗？](https://blog.uiharu.top/archives/computational-neuroscience-1-do-you-know-brain.html)
> fix(style): fix style of post navigation

- layout/common/article.jsx
We can get UTC TZ format time when we **hover** on relative time, it is not friendly, I suggest to change it to locale string.
> feat(layout): change date time format to locale string instead of UTC TZ time

- source/_posts/en/Search-Plugins.md
- source/_posts/zh-CN/Search-Plugins.md
The environment variable in the **set** is a string value. If you add quotation marks, the quotation marks will become part of the value, causing an error.
```
INFO  === Checking package dependencies ===
INFO  === Checking theme configurations ===
INFO  === Registering Hexo extensions ===
INFO  [hexo-algolia] Testing HEXO_ALGOLIA_INDEXING_KEY permissions.
ERROR [hexo-algolia] Invalid Application-ID or API key
ERROR >> You might have used an Admin Key or an invalid Key.
ERROR >> Read https://npmjs.com/hexo-algolia#security-concerns for more informations.
```
> Remove extra quotes

- layout/common/article.jsx
Hide the element when the page title is empty
> feat(layout): hide the element when the page title is empty

- include/schema/common/comment.json
There is a problem with 'visitor' options, it need a container to show the count: [PageViews](https://waline.js.org/guide/client/count.html)
[hexo-component-inferno PR #26](https://github.com/ppoffice/hexo-component-inferno/pull/26)
[hexo-component-inferno #25](https://github.com/ppoffice/hexo-component-inferno/issues/25)
> feat(schema): add Waline comment system.

- include/schema/common/article.json
- layout/common/article.jsx
If the post's updated is same as date, hide the element of
updated time automatically.
Also provides a new config option to toggle this behavior.
Signed-off-by: Weida Hong <wdhongtw@gmail.com>
> feat(layout): add option for updated time of posts

- layout/common/widgets.jsx
- layout/layout.jsx
> 修复了issue #926中提及的漏洞

- include/register.js
- scripts/tags/message.js
- scripts/tags/tabs.js
添加了两个标签（从示例网站中得到灵感）
用法：
**message**:
```
{% message color:danger icon:info-circle 'title:Very danger!' size:small %}
**You are in danger.**
{% endmessage %}
{% message color:danger 'title:Very danger!' size:small %}
**You are in danger.**
{% endmessage %}
{% message color:primary icon:info-circle %}
**You are not in danger.**
{% endmessage %}
{% message color:primary %}
**You are not in danger.**
{% endmessage %}
```
**tabs**:
```
{% tabs behavior:centered style:toggle-rounded %}
This is AADD.
This is Info.
{% endtabs %}
{% tabs behavior:fullwidth size:small style:boxed %}
- assdf
- asd
- aege
- sasd
[sad]()
asd
sdf
- aa
- ff
{% endtabs %}
```
效果：
<https://xfqwdsj.github.io/tags-preview/>
> Added message tag, tabs tag.

- source/js/main.js
This allows users to customize the styles of foldable blocks.
> Add foldable css class for codeblocks

- include/style/codeblock.styl
- source/js/main.js
Before this change, for codeblocks with folding enabled, users have to click the small arrow to toggle fold/unfold:
I find it very difficult to click since it's too small.
After this PR, clicking anywhere in the div below would toggle fold/unfold:
The hyperlink and copy button on the right is unaffected.
Also changed the cursor style to pointer, for this div.
When folding is disabled, the cursor style stays unchanged - this is a use case of https://github.com/ppoffice/hexo-theme-icarus/pull/1071
This is only my personal opinion, so feel free to dismiss it, and I can keep it in my own customization.
> Make codeblock fold/unfold use a larger clickable area

- source/js/animation.js
QuerySelector does not work with ids that start with numbers:
https://stackoverflow.com/questions/20306204/using-queryselector-with-ids-that-are-numbers 
https://github.com/madrobby/zepto/issues/1333
> Fix support for hashes that start with numbers

- include/schema/common/footer.json
- layout/common/footer.jsx
Added custom copyright.
**Example:**
> **Important!Important!Important!** In China, a filing number needs to be set at the bottom of the website for public access, otherwise it will not pass the filing audit.
> feat(footer): added copyright

- layout/widget/profile.jsx
This pull request adds the `me` keyword to the `rel` attribute of certain hyperlinks in the profile widget, allowing users to verify that they are the owner of a page created with Icarus. See, for example, https://joinmastodon.org/verification.
> Add "me" keyword to certain links

- include/schema/common/plugins.json
- include/schema/plugin/pjax.json
- layout/common/head.jsx
- layout/common/scripts.jsx
- layout/plugin/back_to_top.jsx
- layout/plugin/pjax.jsx
- source/js/pjax.js
- Current state: when PJAX completed, reload the whole scripts which contains one or more functions that needs to be reloaded when a page is loaded.
- Next step: when PJAX completed, only reload the functions that needs to be reloaded.
Implements #1277
Related #1269 #992 #722 #649 #507
> feat(core): Add preliminary support for PJAX

- source/js/pjax.js
**#1327** ：使用 pjax 时 MathJax 未在新页面重新加载，从而导致数学公式无法在新页面渲染。
监听 `pjax:complete` 事件。当该事件触发时，判断是否已导入 MathJax。如果已导入，则调用 MathJax 的 `typesetPromise()` 方法来重新渲染数学公式。
-----
**#1327** : Math formulas not rendered in new pages because pjax banned the reloading of MathJax.
Listen on `pjax:complete` event. When the event triggered, see whether MathJax has been imported, then invoke `typesetPromise()` to re-render math formulas.
> fix(view): fix pjax support for mathjax

- source/js/pjax.js
在使用“卜算子”统计插件时，如果启用了 pjax，则会导致切换页面后，卜算子的显示功能失效。例如，文章详情页面的顶部信息栏显示 `0 VISITS`。
这是因为卜算子的 JS 脚本需要重新运行才能生效。卜算子的 JS 源码概述如下：
```javascript
var bszCaller, bszTag;
!function() {
// ...
}(),
bszCaller = {
fetch: function(a, b) {
// ...
},
evalCall: function(a) {
// ...
}
},
bszCaller.fetch("//busuanzi.ibruce.info/busuanzi?jsonpCallback=BusuanziCallback", function(a) {
bszTag.texts(a),
bszTag.shows()
}),
bszTag = {
//...
};
```
可见，必须运行 `bszCaller.fetch(...)` 语句才可以使得页面中的统计文本正常显示。
仿照上次 MathJax 问题的解决方案。只需在 `pjax:complete` 事件触发后，手动运行 `bszCaller.fetch(...)` 语句即可。
> 此外，自从采用了 pjax 技术以来，已经发现了很多类似的不兼容性问题（未来可能也会继续出现），并引入了一定的代码维护复杂度。是否应该考虑一种通用的解决方案（把所有 `<script>` 都打上 `data-pjax` 标签？）来解决这一系列问题？或者弃用 pjax 而采用其他的性能优化方案？
-----
When using the "Busuanzi" statistics plugin, enabling PJAX causes the plugin's display …
> fix(view): fix pjax support for busuanzi
